# Nixpacks configuration for Coolify deployment

[phases.setup]
nixPkgs = ["nodejs"]
aptPkgs = ["openssl", "ca-certificates"]
libs = ["sqlite"]  # SQLite support for database

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx prisma generate", 
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--enable-source-maps"
