# Nixpacks configuration for Coolify deployment

[phases.setup]
nixPkgs = ["nodejs"]
aptPkgs = ["openssl", "ca-certificates"]
libs = ["sqlite"]  # SQLite support for database

[phases.install]
cmds = [
  "npm install -g pnpm@9",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm exec prisma generate", 
  "pnpm build"
]

[start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--enable-source-maps"
